---
title: "Day 3 EOD"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
```

# Conditionals
## Task 1
```{r}
pm2_5 <- 48

if (pm2_5 < 100) {
  print("Low to moderate risk")
} else if (pm2_5 >= 100 & pm2_5 < 150) {
  print("Unhealthy for sensitive groups")
} else if (pm2_5 >= 150) {
  print("Health risk present")
}
```

## Task 2
```{r}
species <- "blue whale"

if (str_detect(species, "whale")) {
  print("You found a whale!")
}
```

## Task 3
```{r}
base_burrito <- 6.50
main_ingredient <- "chicken"

if (main_ingredient == "veggie") {
  print(paste("A veggie burrito costs", base_burrito))
} else if (main_ingredient == "chicken") {
  print(paste("A chicken burrito costs", base_burrito + 3))
} else if (main_ingredient == "steak") {
  print(paste("A steak burrito costs", base_burrito + 3.25))
}
```

# For loops
## Task 4
```{r}
fish <- c(8, 10, 12, 23)
total_fish <- sum(fish)

for (i in seq_along(fish)) {
  print(fish[i] / total_fish)
}
```

## Task 5
```{r}
for (i in seq_along(month.name)) {
  print(paste((month.name[i]), "is month", i))
}
```

